### ISSUE TITLE
Issue about "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by qianliangchang** [yuto3o/SKNet-Keras#2]
Hi boy,
 Thanks for you repo firstly, so nice you are!
 However, There are some confuses when I follow you code, Could you afford some help?
code as follw, I Copy you SKNet code all into my project, but throw "out of range" Exception when I do it
```
U = layers.Add(name=name+'_add')(xs)
    s = layers.Lambda(lambda x:
                      tf.reduce_mean(x, axis=[1, 2], keepdims=True),
                      output_shape=[b, 1, 1, filters],
                      name=name+'_gap')(U)

    z = layers.Conv2D(d, 1, name=name+'_fc_z')(s)
    z = layers.BatchNormalization(name=name+'_fc_z_bn')(z)
    z = layers.Activation('relu', name=name+'_fc_z_relu')(z)
```

Exxeption as follw

```
Traceback (most recent call last):
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/skconv_keras.py", line 98, in <module>
    x = SKConv(3, G=1)(inputs)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/skconv_keras.py", line 45, in wrapper
    z = layers.Conv2D(d, 1, name=name+'_fc_z')(s)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/topology.py", line 638, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/keras/layers/convolutional.py", line 195, in compute_output_shape
    self.kernel_size[i],
IndexError: tuple index out of range
```

Could you help me to fit it? thanks very much!

**Comment by yuto3o** [comment]
Can you provide a complete test case? or just print the info of param 's' in your project. I think any info about the input 's' will help us fix the problem.

**Comment by qianliangchang** [comment]
I just use your code-_" skconv.py"_ without others,  and run _main_  function, 
```
if __name__ == '__main__':
  from keras.layers import Input
  from keras.models import Model

  inputs = Input([None, None, 32])
  # shape = inputs.get_shape
  print(inputs.get_shape())
  x = SKConv(3, G=1)(inputs)

  m = Model(inputs, x)
  m.summary()

  import numpy as np

  X = np.random.random([2, 224, 224, 32]).astype(np.float32)
  y = m.predict(X)
```
errors as follw,
```
/home/ql/anaconda3/envs/tf/bin/python /home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 36475 --file /media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/skconv.py
pydev debugger: process 14087 is connecting

Connected to pydev debugger (build 183.5429.31)
Using TensorFlow backend.
(?, ?, ?, 32)
2019-06-21 20:06:37.645754: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-21 20:06:37.741703: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-06-21 20:06:37.742018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.27GiB
2019-06-21 20:06:37.742029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2019-06-21 20:06:37.912201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-21 20:06:37.912228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2019-06-21 20:06:37.912233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2019-06-21 20:06:37.912354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7025 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ql/work/tools/pycharm-2018.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/skconv.py", line 97, in <module>
    x = SKConv(3, G=1)(inputs)
  File "/media/ql/文档/Document/毕设/YOLO/工程实验/keras-yolo3/yolo3/skconv.py", line 43, in wrapper
    z = layers.Conv2D(d, 1, name=name+'_fc_z')(s)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/topology.py", line 638, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/keras/layers/convolutional.py", line 195, in compute_output_shape
    self.kernel_size[i],
IndexError: tuple index out of range
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f97c3e50e10>>
Traceback (most recent call last):
  File "/home/ql/anaconda3/envs/tf/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable

Process finished with exit code 1
```
thanks for your reply!

and my env as follw:

- keras-gpu                 2.1.5
- tensorflow-gpu            1.8.0 
- python                    3.5.4 
- cudnn                     7.1.3  
- cudatoolkit               8.0

**Comment by yuto3o** [comment]
I run the following code in my pc, everything is ok:
```
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

inputs = Input([None, None, 32])
x = SKConv(3, G=1)(inputs)

m = Model(inputs, x)
m.summary()

import numpy as np

X = np.random.random([2, 224, 224, 32]).astype(np.float32)
y = m.predict(X)
```
log
```
(tensorflow) C:\Users\xxx\Desktop\SKNet-Keras-master>python skconv.py
WARNING:tensorflow:From C:\Users\xxx\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.    
Instructions for updating:
Colocations handled automatically by placer.
__________________________________________________________________________________________________ 
Layer (type)                    Output Shape         Param #     Connected to
================================================================================================== 
input_1 (InputLayer)            (None, None, None, 3 0
__________________________________________________________________________________________________ 
skconv_conv1 (Conv2D)           (None, None, None, 3 9216        input_1[0][0]
__________________________________________________________________________________________________ 
skconv_conv2 (Conv2D)           (None, None, None, 3 9216        input_1[0][0]
__________________________________________________________________________________________________ 
__________________________________________________________________________________________________
skconv_gap (Lambda)             (None, 1, 1, 32)     0           skconv_add[0][0]
__________________________________________________________________________________________________
skconv_fc_z (Conv2D)            (None, 1, 1, 32)     1056        skconv_gap[0][0]
__________________________________________________________________________________________________
skconv_fc_z_bn (BatchNormalizat (None, 1, 1, 32)     128         skconv_fc_z[0][0]
__________________________________________________________________________________________________
skconv_fc_z_relu (Activation)   (None, 1, 1, 32)     0           skconv_fc_z_bn[0][0]
__________________________________________________________________________________________________
skconv_fc_x (Conv2D)            (None, 1, 1, 96)     3168        skconv_fc_z_relu[0][0]
__________________________________________________________________________________________________
skconv_reshape (Reshape)        (None, 1, 1, 32, 3)  0           skconv_fc_x[0][0]
__________________________________________________________________________________________________
skconv_softmax (Softmax)        (None, 1, 1, 32, 3)  0           skconv_reshape[0][0]
__________________________________________________________________________________________________
skconv_stack (Lambda)           (None, None, None, 3 0           skconv_conv1_relu[0][0]
                                                                 skconv_conv2_relu[0][0]
                                                                 skconv_conv3_relu[0][0]
__________________________________________________________________________________________________
skconv_axpby (Axpby)            (None, None, None, 3 0           skconv_softmax[0][0]
                                                                 skconv_stack[0][0]
==================================================================================================
Total params: 32,384
Trainable params: 32,128
Non-trainable params: 256
__________________________________________________________________________________________________
2019-06-24 14:59:56.677704: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
```
ENV is as follows:
python                      3.7.3
tensorflow                1.13.1

**Comment by qianliangchang** [comment]
Thanks for your help, In fact, your code is OK. everything is normal when running in **terminal** , but throws this exception when running in **pycharm**. maybe my **pycharm** has some problems.   anyway, it's OK in terminal. thanks again!
